"""RAG service for receipt item subcategory classification.

Pipeline position: after keyword-rule matching, before regex fallback.

Embeddings are generated by Ollama (embeddinggemma:latest by default).
Similarity search uses pgvector cosine distance on the item_embeddings table.

Visibility rules mirror ItemKeywordRule:
  - is_global=True  → matches any user (admin-uploaded knowledge base)
  - is_global=False → matches only the owning user (auto-created from corrections)
"""

from __future__ import annotations

import uuid

import httpx
import structlog
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.item_embedding import ItemEmbedding

logger = structlog.get_logger(__name__)


async def get_embedding(text: str) -> list[float] | None:
    """Call Ollama /api/embeddings and return the embedding vector, or None on error."""
    url = f"{settings.ollama_url}/api/embeddings"
    payload = {"model": settings.ollama_embedding_model, "prompt": text.strip()}
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(url, json=payload)
            response.raise_for_status()
            data = response.json()
            embedding = data.get("embedding")
            if not isinstance(embedding, list) or not embedding:
                logger.warning("item_rag.embedding.empty_response", model=settings.ollama_embedding_model)
                return None
            return embedding
    except Exception as exc:
        logger.warning("item_rag.embedding.failed", error=str(exc), model=settings.ollama_embedding_model)
        return None


async def find_similar_subcategory(
    db: AsyncSession,
    user_id: uuid.UUID,
    description: str,
) -> tuple[str, float] | None:
    """Return (subcategory_label, confidence) for the most similar known item, or None.

    Searches both the user's private embeddings and global ones.
    Returns None if no match is within settings.rag_similarity_threshold (cosine distance).
    """
    embedding = await get_embedding(description)
    if embedding is None:
        return None

    distance_col = ItemEmbedding.embedding.cosine_distance(embedding).label("distance")
    result = await db.execute(
        select(ItemEmbedding, distance_col)
        .where(
            or_(
                ItemEmbedding.is_global.is_(True),
                ItemEmbedding.user_id == user_id,
            )
        )
        .order_by(distance_col)
        .limit(1)
    )
    row = result.first()
    if row is None:
        return None

    entry, distance = row
    if distance > settings.rag_similarity_threshold:
        logger.debug(
            "item_rag.no_match",
            description=description[:60],
            best_distance=round(float(distance), 4),
            threshold=settings.rag_similarity_threshold,
        )
        return None

    # Convert cosine distance [0, 2] → confidence [0, 1]
    confidence = round(max(0.0, min(1.0, 1.0 - (float(distance) / 2.0))), 3)
    logger.debug(
        "item_rag.match",
        description=description[:60],
        matched=entry.description_text[:60],
        subcategory=entry.subcategory_label,
        distance=round(float(distance), 4),
        confidence=confidence,
    )
    return entry.subcategory_label, confidence


async def upsert_item_embedding(
    db: AsyncSession,
    *,
    description: str,
    subcategory_label: str,
    user_id: uuid.UUID,
    is_global: bool = False,
    source: str = "correction",
    notes: str | None = None,
) -> ItemEmbedding | None:
    """Embed *description* and store it (or skip if embedding fails or duplicate).

    Deduplicates by (description_text, subcategory_label, user_id, is_global).
    Returns the created entry, or None if embedding failed or already exists.
    """
    normalized = description.strip()[:300]
    if not normalized:
        return None

    existing = await db.execute(
        select(ItemEmbedding).where(
            ItemEmbedding.description_text == normalized,
            ItemEmbedding.subcategory_label == subcategory_label,
            ItemEmbedding.user_id == user_id,
            ItemEmbedding.is_global == is_global,
        )
    )
    if existing.scalar_one_or_none() is not None:
        return None

    embedding = await get_embedding(normalized)
    if embedding is None:
        return None

    entry = ItemEmbedding(
        user_id=user_id,
        is_global=is_global,
        description_text=normalized,
        embedding=embedding,
        subcategory_label=subcategory_label,
        source=source,
        notes=notes,
    )
    db.add(entry)
    await db.flush()
    return entry


async def bulk_upsert_embeddings(
    db: AsyncSession,
    *,
    entries: list[tuple[str, str]],
    user_id: uuid.UUID,
    is_global: bool,
    source: str = "document",
    notes: str | None = None,
) -> int:
    """Embed and store multiple (description, subcategory) pairs. Returns count inserted."""
    inserted = 0
    for description, subcategory_label in entries:
        result = await upsert_item_embedding(
            db,
            description=description,
            subcategory_label=subcategory_label,
            user_id=user_id,
            is_global=is_global,
            source=source,
            notes=notes,
        )
        if result is not None:
            inserted += 1
    return inserted
