"""Receipt storage, OCR, and validated extraction helpers for SpendHound."""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path

from fastapi import UploadFile
from pydantic import BaseModel, Field
from pypdf import PdfReader

from app.config import settings
from app.services.llm.base import LLMConfig, Message
from app.services.llm.factory import get_llm_provider
from app.services.spendhound import resolve_category


class ReceiptPreviewModel(BaseModel):
    merchant: str = Field(default="")
    amount: float | None = Field(default=None)
    currency: str = Field(default=settings.default_currency)
    expense_date: str | None = Field(default=None)
    description: str | None = Field(default=None)
    category_name: str | None = Field(default=None)
    notes: str | None = Field(default=None)
    confidence: float = Field(default=0.35, ge=0, le=1)


@dataclass
class StoredReceipt:
    stored_filename: str
    storage_path: str
    file_size: int


async def store_upload(user_id: uuid.UUID, upload: UploadFile) -> StoredReceipt:
    receipt_dir = Path(settings.receipt_storage_dir) / str(user_id)
    receipt_dir.mkdir(parents=True, exist_ok=True)
    suffix = Path(upload.filename or "receipt").suffix
    stored_filename = f"{uuid.uuid4()}{suffix}"
    target_path = receipt_dir / stored_filename
    content = await upload.read()
    target_path.write_bytes(content)
    return StoredReceipt(stored_filename=stored_filename, storage_path=str(target_path), file_size=len(content))


async def extract_text_from_file(storage_path: str, content_type: str | None) -> str:
    path = Path(storage_path)
    file_bytes = path.read_bytes()
    if (content_type or "").startswith("text/"):
        return file_bytes.decode("utf-8", errors="ignore").strip()
    if path.suffix.lower() == ".pdf":
        try:
            reader = PdfReader(storage_path)
            return "\n".join((page.extract_text() or "") for page in reader.pages).strip()
        except Exception:
            return ""
    return ""


def _extract_json_object(raw_text: str) -> dict | None:
    start = raw_text.find("{")
    end = raw_text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        return json.loads(raw_text[start : end + 1])
    except json.JSONDecodeError:
        return None


def fallback_preview_from_text(text: str, filename: str) -> ReceiptPreviewModel:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    merchant = lines[0][:255] if lines else Path(filename).stem.replace("_", " ").title()
    amount_match = re.search(r"(?:€|EUR|\$)?\s*(\d+[\.,]\d{2})", text)
    amount = None
    if amount_match:
        try:
            amount = float(amount_match.group(1).replace(",", "."))
        except ValueError:
            amount = None
    date_match = re.search(r"(\d{4}-\d{2}-\d{2}|\d{2}[/-]\d{2}[/-]\d{4})", text)
    expense_date = None
    if date_match:
        candidate = date_match.group(1).replace("/", "-")
        if re.fullmatch(r"\d{2}-\d{2}-\d{4}", candidate):
            day, month, year = candidate.split("-")
            expense_date = f"{year}-{month}-{day}"
        else:
            expense_date = candidate
    return ReceiptPreviewModel(
        merchant=merchant,
        amount=amount,
        expense_date=expense_date,
        description=lines[1][:300] if len(lines) > 1 else None,
        notes="Generated by local fallback extraction.",
        confidence=0.4 if amount else 0.25,
    )


async def llm_receipt_preview(text: str, filename: str, llm_config: LLMConfig | None) -> ReceiptPreviewModel | None:
    if not text.strip():
        return None
    try:
        provider = get_llm_provider(llm_config)
        response = await provider.complete(
            [
                Message(
                    role="system",
                    content=(
                        "You extract expense receipt fields into strict JSON only. Return one object with keys: merchant, amount, currency, expense_date, description, category_name, notes, confidence. Use null where unknown."
                    ),
                ),
                Message(
                    role="user",
                    content=(
                        f"Filename: {filename}\nReceipt text follows. Infer the best structured expense draft.\n\n{text[:8000]}"
                    ),
                ),
            ],
            llm_config,
        )
        payload = _extract_json_object(response)
        if payload is None:
            return None
        model = ReceiptPreviewModel.model_validate(payload)
        if model.amount is not None and model.amount <= 0:
            model.amount = None
        return model
    except Exception:
        return None


async def build_receipt_preview(db, user_id: uuid.UUID, *, text: str, filename: str, llm_config: LLMConfig | None) -> ReceiptPreviewModel:
    preview = await llm_receipt_preview(text, filename, llm_config)
    if preview is None:
        preview = fallback_preview_from_text(text, filename)
    if preview.category_name is None and preview.merchant:
        category = await resolve_category(db, user_id, merchant=preview.merchant)
        if category is not None:
            preview.category_name = category.name
            preview.confidence = max(preview.confidence, 0.72)
    if preview.amount is not None:
        try:
            preview.amount = float(Decimal(str(preview.amount)).quantize(Decimal("0.01")))
        except (InvalidOperation, ValueError):
            preview.amount = None
    if not preview.currency:
        preview.currency = settings.default_currency
    return preview


def create_llm_config(*, provider: str | None, model: str | None, api_key: str | None, base_url: str | None) -> LLMConfig | None:
    if not any([provider, model, api_key, base_url]):
        return None
    return LLMConfig(provider=provider or None, model=model or None, api_key=api_key or None, base_url=base_url or None)
